### ISSUE TITLE
Sender from msg can't be used for MimeMessage

### ISSUE THREAD

**Issue by jboesl** [ctabin/jotlmsg#2]
I get an an exception when I try to create a MimeMessage from a OutlookMessage:
```
Caused by: javax.mail.internet.AddressException: Local address contains control or whitespace in string ``Tim Toner''
	at javax.mail.internet.InternetAddress.checkAddress(InternetAddress.java:1353)
	at javax.mail.internet.InternetAddress.parse(InternetAddress.java:1213)
	at javax.mail.internet.InternetAddress.parse(InternetAddress.java:752)
	at javax.mail.internet.InternetAddress.<init>(InternetAddress.java:119)
	at ch.astorm.jotlmsg.OutlookMessage.toMimeMessage(OutlookMessage.java:371)
	at ch.astorm.jotlmsg.OutlookMessage.toMimeMessage(OutlookMessage.java:352)
	at ch.astorm.jotlmsg.OutlookMessage.toMimeMessage(OutlookMessage.java:339)
	at de.adito.msgconverter.Msg2eml.<init>(Msg2eml.java:31)
```

I were able to find the sender E-Mail address in the 'unknown chunks' in 'org.apache.poi.hsmf.MAPIMessage' but the actual field for the address is empty. Only the name is supplied.

**Comment by ctabin** [comment]
Hello, can you provide the `.msg` file you used ? Not sure if the bug is really in jotlmsg or in the underlying apache library (actually jotlmsg only writes/converts the message, but does not read it).

**Comment by jboesl** [comment]
Sorry I can't provide it since it's a company mail. But I can tell you that the parameter passed to 'new InternetAddress' is in the format 'surename lastname' and that causes the exception.

**Comment by ctabin** [comment]
@jboesl I wrote a check in #4, maybe you can just look at the tests to see if your case is tested ? Thanks !

**Comment by jboesl** [comment]
That covers my case. I should receive 'null' now for the from field but not get an exception any longer.
